# Generated by Django 2.2.12 on 2021-01-13 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Echipa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Meci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('echipa1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ech1', to='sportifyapp.Echipa')),
                ('echipa2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ech2', to='sportifyapp.Echipa')),
            ],
        ),
        migrations.CreateModel(
            name='Jucator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenume', models.CharField(max_length=20)),
                ('nume', models.CharField(max_length=20)),
                ('varsta', models.IntegerField()),
                ('echipa', models.ManyToManyField(to='sportifyapp.Echipa')),
            ],
        ),
        migrations.AddField(
            model_name='echipa',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportifyapp.Sport'),
        ),
    ]
